### PR TITLE
Change version of kcov downloaded

### PR DESCRIPTION
**Pull request by Kerollmops**
this could probably fix the issue #58

### CODE REVIEW

**Comment by autohuonw** [comment]
Thanks for the pull request, and welcome! You should hear from @huonw (or someone else) soon.

**Comment by Kerollmops** [comment]
No, That don't fix anything...

**Comment by johanneskoester** [comment]
@Kerollmops I think this is still a good idea. For example, I get [this error](https://travis-ci.org/rust-bio/rust-bio/jobs/193051124#L1088), which looks like kcov changed its command line arguments. Hence, I'd say going back to the version before the last travis-cargo release (v31) should make this work again and also maybe fix the upload problems.

**Comment by Kerollmops** [comment]
Yup that's why I try to do but that just change nothing sadly 😞

**Comment by johanneskoester** [comment]
Can you say in what sense (what exactly is your error) and with which version? I thin v31 instead of v32 should help in this case.

**Comment by Kerollmops** [comment]
I get the same error as you, I tried to change the kcov version but that change nothing...

**Comment by johanneskoester** [comment]
Did you change it to v31?

**Comment by Kerollmops** [comment]
nope, but you can, just fork and test, if it work I am ready to see that ! 😄

**Comment by johanneskoester** [comment]
I have a fix in PR #66.

**Comment by Kerollmops** [comment]
That's great, I subscribe to the thread !
Thanks

**Pull request closed without merging**
