### PR TITLE
fix bug in error message case

### PR DESCRIPTION
**Pull request by droundy**
This error manifested as:

Traceback (most recent call last):
  File "/home/travis/.local/bin/travis-cargo", line 11, in <module>
    sys.exit(main())
  File "/home/travis/.local/lib/python2.7/site-packages/travis_cargo.py", line 349, in main
    manifest = Manifest(os.getcwd(), version)
  File "/home/travis/.local/lib/python2.7/site-packages/travis_cargo.py", line 40, in __init__
    ' and `--manifest-path {}`:' % (path_file, path_dir),
TypeError: not all arguments converted during string formatting

### CODE REVIEW

**Comment by autohuonw** [comment]
Thanks for the pull request, and welcome! You should hear from @huonw (or someone else) soon.

**Comment by huonw** [comment]
Oh, whoops! This looks like it is a mistake of using `%` instead of `.format`, so the fix should be changing it to

```python
'and `--manifest-path {}`:'.format(path_file, path_dir)
```

**Comment by autohuonw** [comment]
:umbrella: The latest upstream changes (presumably #40) made this pull request unmergeable. Please resolve the merge conflicts.

**Comment by huonw** [comment]
This was fixed in #40; thanks though!

**Pull request closed without merging**
