### PR TITLE
Fix hoverbear links in README.md

### PR DESCRIPTION
**Pull request by bluss**
This link changed slightly unfortunately, blog software mishap.

### CODE REVIEW

**Comment by autohuonw** [comment]
Thanks for the pull request, and welcome! You should hear from @huonw (or someone else) soon.

**Comment by huonw** [comment]
@autohuonw r+

**Comment by autohuonw** [comment]
:pushpin: Commit 67d6fbb has been approved by `huonw`

**Comment by autohuonw** [comment]
:hourglass: Testing commit 67d6fbb with merge efac123...

**Comment by bluss** [comment]
This never landed, seems to be fixed on the remote end.

**Comment by huonw** [comment]
Oh, whoops, I just assumed this landed.

**Pull request closed without merging**
