### PR TITLE
Add setup.py with entry point for easy installation.

### PR DESCRIPTION
**Pull request by jansegre**
**Note:** moving `travis-cargo.py` to `travis_cargo.py` is a breaking change required for it to be a valid module, an alternative would be a symlink but it may be acceptable to break this early.

This is the least step for having package which can be installed with `pip`, some more metadata and it can go straight to PyPI.

The intended usage is:

```yaml
language: rust
rust:
- nightly
- beta
sudo: false
before_script:
- pip install git+https://github.com/jansegre/travis-cargo.git --user $USER && export PATH=$HOME/.local/bin:$PATH
script:
- travis-cargo cargo build
- travis-cargo cargo test
- travis-cargo cargo doc
after_success:
- travis-cargo --only beta doc-upload
env:
  global:
    secure: <your GH_TOKEN secured var>
```

Once on PyPI it could be installed as simple as:
```
pip install travis-cargo --user $USER && export PATH=$HOME/.local
```

I almost put a 'tc' entry point, though after seeing that local pip is not on path and there is a system tc I left it as travis-cargo, later I saw your commit that changed to ./tc because of that. I'm mildly annoyed by writing `travis-cargo cargo` instead of `./tc cargo` or just `travis-cargo`, though my quick attempt to flat the subparsers went wrong I'll stick with the long `travis-cargo cargo` because I'm more comfortable with that way of installing and would be even more if it was on PyPI.

Besides that I think it's worth making it more clear that the github token variable is named `GH_TOKEN`, other projects seem to use `TOKEN`.

Anyway, great script, will definitely use for all my rust projects.

### CODE REVIEW

**Comment by huonw** [comment]
Hm, it would be good to try to make this less of a breaking change. I wonder if we could ease the migration with a `travis-cargo.py` containing something like:

```python
print('''project layout was changed. Use one of the following instead:
- to invoke the script with `travis-cargo`:
    pip install git+https://github.com/huonw/travis-cargo.git --user $USER && export PATH=$HOME/.local/bin:$PATH

- to invoke the script with `./tc`:
    pip install git+https://github.com/huonw/travis-cargo.git --user $USER && ln -s $HOME/.local/bin/travis-cargo tc
''')
exit(1)
```

**Comment by huonw** [comment]
(Thanks for the PR! I know stuff about cargo, but not about pip. :P )

**Comment by jansegre** [comment]
Yeah, I should've made it non-breaking to begin with it was simple enough.

Anyway these two builds show different usages. Both work, though with travis-cargo.py it just prints a warning, maybe it shouldn't and both be supported:

- https://travis-ci.org/jansegre/phi/builds/60683979
- https://travis-ci.org/jansegre/phi/builds/60640035

**Comment by huonw** [comment]
Hm, I'm not sure just printing is "good enough". Personally, I'd be unlikely to notice a change like that in my travis logs (especially with `--verbose` on), as you said before, it's still early in the life of the script, so I'd prefer to just break everyone's builds to ensure they see the error message (as sad as that is).

I suppose I should really think about better forwards compatibility for future changes. Hm.

**Comment by huonw** [comment]
(I'd be very happy to hear if you have any ideas about that. :smile:)

**Comment by jansegre** [comment]
Hmmm, if published to PyPI semver can be used, like so:

    pip install 'travis-cargo<2.0' --user $USER && export PATH=$HOME/.local/bin:$PATH

If a breaking change is introduced users that want the new version would use

    pip install 'travis-cargo<3.0' --user $USER && export PATH=$HOME/.local/bin:$PATH

If a non-breaking change is published it will be used on new builds. Or maybe it can be made to never break.

(Actually PyPI is not really required I think if the project is tagged the github repo can be used as a source for the package name, but I think it would be awesome to install it with a simple `pip install travis-cargo`).

I don't have a strong opinion on using `pip install ... && export PATH=$HOME/.local/bin:$PATH` over `pip install ... && ln -s $HOME/.local/bin/travis-cargo tc`.

Another possibility would be to use another shorter command name, like `tcs` (travis-cargo script), `traca` or `tra` or even `t-c`, or `tcau` (travis-cargo utilities).

Anyway, it seems better to break but loudly not silently. Though I like better the idea of having a single way to use, either `./tc` or `travis-cargo` or something else. I'll just add the loud breaking for now.

**Comment by huonw** [comment]
Good idea! Do you happen to know if a package can force that it is installed with an explicit version specified in some form? (i.e. make a plain `pip install 'travis-cargo'` illegal) I guess this might be a horrible horrible hack and/or solving the wrong problem.

Using a different name is a good idea, but, unfortunately, I'm not keen on any of your suggestions.

Hm, I wonder if the script could just change to `travis-cargo test ...` etc., as you suggest, and it would manually detect `travis-cargo doc-upload` and any other subcommands separately. I'll experiment.

(I have a few other changes I wish to make before landing this breaking change, so this PR is essentially accepted, but I'll not merge to master just yet.)

**Comment by huonw** [comment]
> it would manually detect travis-cargo doc-upload and any other subcommands separately

Ok, I have this mostly working (current wip https://github.com/huonw/travis-cargo/commit/6ccb9a23a141f5d5278a057a8b197b994ded3e9a), so I think we can probably just go with that and avoid the `./tc` stuff altogether. I'm happy to edit the deprecation message to reflect this when I put everything together for the push to master (so you don't need to keep up with my changes, thoguh you can if you wish, of course :) ).

**Comment by jansegre** [comment]
I don't think it's a good idea to make a plain install illegal, and that would be probably impossible, the closest way to do that would be not to publish to PyPI and make the way to install it through explicit github branches.

I think that `travis-cargo <single command>` design is great and worth freezing. I hope this gets published to PyPI, and I'm very glad I could help somehow :)

**Comment by huonw** [comment]
Ok, I guess I'll just put a big warning that I'm not guaranteeing back-compat for installations without a constrained version.

I'll publish on PyPI once I finish the last feature: integration with coveralls.io for code coverage: `travis-cargo coveralls` will record and upload coverage information (and once I work out how to publish :P ).

Thanks for your help!

**Comment by huonw** [comment]
Thanks again!

I published to PyPI and wrote http://huonw.github.io/blog/2015/05/travis-on-the-train-part-2/

**Comment by jansegre** [comment]
Wow, nice! Thanks!

**Pull request merged**
